[workspace]
members = [
    "server",
    "desktop",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.3.0"

[workspace.dependencies]
serde_json = "1"
chrono-tz = "0.10"
futures = "0.3"
tracing = "0.1"

[workspace.dependencies.dioxus]
version = "0.7.7"
features = [
    "fullstack",
    "router",
]

[workspace.dependencies.serde]
version = "1"
features = ["derive"]

[workspace.dependencies.chrono]
version = "0.4"
features = ["serde"]

[workspace.dependencies.uuid]
version = "1"
features = [
    "v4",
    "serde",
]

[workspace.dependencies.tokio]
version = "1"
features = ["full"]

[profile.dev]
debug = "line-tables-only"
