---

services:

  app:
    build:
      context: .
    container_name: lets-chat-dev
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      RUST_LOG: debug
    volumes:
      - ./src:/app/src
      - ./assets:/app/assets
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - ./migrations:/app/migrations
      - cargo_target:/app/target
      - lets_chat_data:/data

volumes:
  cargo_target:
  lets_chat_data:
