//! LC-77 address -> resolution.
//!
//! The IMAP-poll model's load-bearing uncertainty: the destination
//! address (either `<inbox-secret>@<ingress-domain>` for per-room ingress
//! OR `reply-<token>@<ingress-domain>` for LC-77-REPLY stage 2 reply-by-
//! email) can land in any of several recipient headers depending on how
//! the operator routes mail into the polled mailbox. We check, in order:
//!
//!   1. `Delivered-To` (set by the receiving MTA on actual delivery)
//!   2. `X-Original-To` (set by some MTAs when forwarding)
//!   3. `To`
//!   4. `Cc`
//!
//! First header whose local-part resolves wins. The two namespaces are
//! disambiguated by the `reply-` prefix on the local part (case-
//! insensitive): a local part starting with `reply-` is treated as a
//! reply-token attempt (LC-77-REPLY) and is NEVER HMAC-hashed against
//! the per-room inbox secret table. Anything else is tried against the
//! inbox-secret HMAC table.
//!
//! Per-room inbox secrets generated by `auth::generate_api_token` carry
//! an `lc_` prefix, so the two namespaces cannot collide structurally.
//!
//! No match in any header -> `NotFound`. Operator deployment docs
//! (`docs/email-ingress.md`) must pin the header-precedence expectation;
//! if a forwarder strips these headers the feature breaks and the
//! operator's only diagnostic is the `tried_addresses` list in the drop
//! log.

use mail_parser::{HeaderValue, Message};

use crate::db::email_inbox::{self, EmailInboxAuth};
use crate::db::reply_tokens::{self, ReplyTokenRow};

/// Prefix on the local part of a reply-by-email Reply-To address. Kept
/// here (not at the dispatcher) because the resolver is the source of
/// truth for namespace discrimination; the dispatcher imports this when
/// constructing the outbound `Reply-To` header.
pub const REPLY_PREFIX: &str = "reply-";

/// Outcome of trying to resolve a polled message's recipient to either
/// a per-room ingress inbox (`<secret>@<domain>`) or a reply-by-email
/// token (`reply-<token>@<domain>`).
#[derive(Debug, Clone)]
pub enum ResolveOutcome {
    /// Active per-room inbox; the caller posts the message via the
    /// email-inbox synthetic actor.
    Match(EmailInboxAuth),
    /// Secret matched a known per-room inbox but the inbox is revoked.
    /// The caller drops with `DropReason::RevokedInbox`.
    Revoked(EmailInboxAuth),
    /// Active reply-by-email token; the caller posts the message as the
    /// real user identified by `user_id` (LC-77-REPLY stage 2).
    ReplyMatch(ReplyTokenRow),
    /// Reply-token row exists but its `expires_at` is in the past. The
    /// caller drops with `DropReason::ReplyExpired` so an operator log
    /// can distinguish a late reply from a garbage `reply-` address.
    ReplyExpired(ReplyTokenRow),
    /// No address in any of the four headers matched a known per-room
    /// inbox or reply-token. `tried_addresses` is the comma-joinable list
    /// the drop log emits so an operator can see exactly which addresses
    /// the resolver saw.
    NotFound { tried_addresses: Vec<String> },
}

/// Header lookup order, exported as a constant so the docs and a
/// `tried_addresses` log can stay in lockstep with the code.
pub const HEADER_ORDER: &[&str] = &["Delivered-To", "X-Original-To", "To", "Cc"];

/// Resolve a polled message to either a per-room inbox row OR an active
/// reply-token. `ingress_domain` is the configured `<domain>` part;
/// addresses whose domain (case-insensitive) does not match are skipped
/// during scan so stray recipient headers (e.g. a Bcc to a personal
/// address that also landed in this mailbox) cannot accidentally hit
/// either namespace.
///
/// `secret_key` is the process-wide HMAC key used to hash a per-room
/// inbox address's local part into the form stored in
/// `email_inboxes.secret_hash`. Reply-token addresses are looked up by
/// the plaintext suffix directly (the token IS the credential; see
/// `db::reply_tokens` for the security model).
pub async fn resolve_address(
    pool: &sqlx::SqlitePool,
    secret_key: &[u8; 32],
    message: &Message<'_>,
    ingress_domain: &str,
) -> sqlx::Result<ResolveOutcome> {
    let mut tried: Vec<String> = Vec::new();
    let domain_lc = ingress_domain.to_ascii_lowercase();

    for header_name in HEADER_ORDER {
        for addr in addresses_from_header(message, header_name) {
            tried.push(addr.clone());
            let Some((local, domain)) = split_addr(&addr) else {
                continue;
            };
            if !domain.eq_ignore_ascii_case(&domain_lc) {
                continue;
            }
            // Namespace fork: the `reply-` prefix is reserved for the
            // LC-77-REPLY reply-token table; the per-room inbox table is
            // queried only when the prefix is absent. We never fall back
            // from one namespace to the other on a miss inside a single
            // address: a `reply-<token>` that doesn't resolve in the
            // reply table will not be HMAC-tried against the inbox table.
            if let Some(suffix) = strip_reply_prefix(local) {
                if let Some((row, expired)) =
                    reply_tokens::resolve_active_or_expired(pool, suffix).await?
                {
                    if expired {
                        return Ok(ResolveOutcome::ReplyExpired(row));
                    }
                    return Ok(ResolveOutcome::ReplyMatch(row));
                }
                continue;
            }
            let secret_hash = crate::auth::hash_api_token(secret_key, local);
            if let Some(row) = email_inbox::find_by_secret_hash(pool, &secret_hash).await? {
                if row.revoked_at.is_some() {
                    return Ok(ResolveOutcome::Revoked(row));
                }
                return Ok(ResolveOutcome::Match(row));
            }
        }
    }

    Ok(ResolveOutcome::NotFound {
        tried_addresses: tried,
    })
}

/// Return the suffix if `local` starts with the `reply-` namespace
/// prefix (case-insensitive). Returns `None` for any other shape so the
/// caller falls through to the per-room inbox HMAC path.
fn strip_reply_prefix(local: &str) -> Option<&str> {
    if local.len() <= REPLY_PREFIX.len() {
        return None;
    }
    let (head, tail) = local.split_at(REPLY_PREFIX.len());
    if head.eq_ignore_ascii_case(REPLY_PREFIX) {
        Some(tail)
    } else {
        None
    }
}

/// Extract every address string from headers matching `header_name`
/// (case-insensitive). Walks `message.headers()` rather than calling
/// the typed `Message::header(HeaderName)` accessor so an
/// operator-set custom header (`X-Original-To`, anything mail-parser
/// doesn't know about as a structured-address header) still surfaces.
fn addresses_from_header(message: &Message<'_>, header_name: &str) -> Vec<String> {
    let mut out = Vec::new();
    for h in message.headers() {
        if !h.name.as_str().eq_ignore_ascii_case(header_name) {
            continue;
        }
        push_from_value(&h.value, &mut out);
    }
    out
}

fn push_from_value(value: &HeaderValue<'_>, out: &mut Vec<String>) {
    match value {
        HeaderValue::Address(mail_parser::Address::List(list)) => {
            for a in list {
                if let Some(s) = a.address.as_deref() {
                    let trimmed = s.trim();
                    if !trimmed.is_empty() {
                        out.push(trimmed.to_string());
                    }
                }
            }
        }
        HeaderValue::Address(mail_parser::Address::Group(groups)) => {
            for g in groups {
                for a in &g.addresses {
                    if let Some(s) = a.address.as_deref() {
                        let trimmed = s.trim();
                        if !trimmed.is_empty() {
                            out.push(trimmed.to_string());
                        }
                    }
                }
            }
        }
        HeaderValue::Text(t) => {
            let trimmed = t.trim();
            if !trimmed.is_empty() {
                out.push(trimmed.to_string());
            }
        }
        HeaderValue::TextList(list) => {
            for t in list {
                let trimmed = t.trim();
                if !trimmed.is_empty() {
                    out.push(trimmed.to_string());
                }
            }
        }
        _ => {}
    }
}

/// Split `local@domain` into `(local, domain)`. Returns `None` if there is
/// no `@` or either side is empty. We do not normalize the local part
/// (RFC 5321 says it's case-sensitive); the secret token alphabet is
/// case-preserved already by `auth::hash_api_token`.
fn split_addr(addr: &str) -> Option<(&str, &str)> {
    let (local, domain) = addr.rsplit_once('@')?;
    if local.is_empty() || domain.is_empty() {
        return None;
    }
    Some((local, domain))
}
