[application]
name = "lets-chat"
default_platform = "web"

[web.app]
title = "Let's Chat"

[web.resource.dev]
style = ["tailwind-built.css", "main.css"]

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
